
INSERT INTO LIBRARY_DB.LIBRARY_USER (USER_NAME, PASSWORD) VALUES ('tom@fpl.com','tom');
INSERT INTO LIBRARY_DB.LIBRARY_USER (USER_NAME, PASSWORD) VALUES ('diane@fpl.com','diane');
INSERT INTO LIBRARY_DB.LIBRARY_USER (USER_NAME, PASSWORD) VALUES ('ellen@fpl.com','ellen');

INSERT INTO LIBRARY_DB.LIBRARY_ROLE (ROLE_NAME) VALUES ('ROLE_ADD_BOOKS');
INSERT INTO LIBRARY_DB.LIBRARY_ROLE (ROLE_NAME) VALUES ('ROLE_SEARCH_BOOKS');

INSERT INTO LIBRARY_DB.LIBRARY_USER_ROLE (USER_ID, ROLE_ID) VALUES (1,1);
INSERT INTO LIBRARY_DB.LIBRARY_USER_ROLE (USER_ID, ROLE_ID) VALUES (1,2);
INSERT INTO LIBRARY_DB.LIBRARY_USER_ROLE (USER_ID, ROLE_ID) VALUES (2,1);
INSERT INTO LIBRARY_DB.LIBRARY_USER_ROLE (USER_ID, ROLE_ID) VALUES (3,2);

INSERT INTO LIBRARY_DB.LIBRARY_BOOK (BOOK_NAME, AUTHOR_FIRST_NAME, AUTHOR_LAST_NAME, ISBN, CATEGORY) 
	VALUES ('Gone with the Wind','Margaret', 'Mitchell', '12345678', 'Classics');
INSERT INTO LIBRARY_DB.LIBRARY_BOOK (BOOK_NAME, AUTHOR_FIRST_NAME, AUTHOR_LAST_NAME, ISBN, CATEGORY) 
	VALUES ('War and Peace','Leo', 'Tolstoy', '87654321', 'Classics');
INSERT INTO LIBRARY_DB.LIBRARY_BOOK (BOOK_NAME, AUTHOR_FIRST_NAME, AUTHOR_LAST_NAME, ISBN, CATEGORY) 
	VALUES ('The Secret','Rhonda', 'Byrne', '11111111', 'Self-help');
INSERT INTO LIBRARY_DB.LIBRARY_BOOK (BOOK_NAME, AUTHOR_FIRST_NAME, AUTHOR_LAST_NAME, ISBN, CATEGORY) 
	VALUES ('The Da Vinci Code','Dan', 'Brown', '12121212', 'Thriller');
INSERT INTO LIBRARY_DB.LIBRARY_BOOK (BOOK_NAME, AUTHOR_FIRST_NAME, AUTHOR_LAST_NAME, ISBN, CATEGORY) 
	VALUES ('The Body Farm','Patricia', 'Cornwell', '13131313', 'Thriller');	